### ISSUE TITLE
Browsing history access?

### ISSUE THREAD

**Issue by bristol-d** [migteam/better-trello-browser-extension#5]
Hi, when the extension updated a couple of days ago, chrome disabled it and said I had to accept the new permission "Access your browsing history" to enable it again.

Just checking what this is, as I care a lot about security - some kind of change to the `chrome.tabs` permission maybe?

The change seems to have come in from 1.4 to 1.5.

**Comment by sewerynkalemba** [comment]
Hi @bristol-d,

So, this permission was added in order to make our new feature of adding websites as Trello cards work. I had no idea it's described in such way (which sounds scary indeed lol), but what the extension essentially does is just quering the active tab and fetching its url, favicon and name.

It's solely used in this file only: https://github.com/migteam/better-trello-browser-extension/blob/main/components/add-to-trello.tsx 

Let me know, if you have any concerns.

**Comment by sewerynkalemba** [comment]
To be fair, `tabs` permission doesn't let the extension access the browsing history, per: 
> Technically this permission allows observing the history via chrome.tabs.onUpdated, but not read the previously existing history, so the phrasing is not entirely correct, strictly speaking.
https://stackoverflow.com/a/64063834/4256320

Actually, I might be able to change that permission to `activeTab` one. I will check if that's possible without regressing this feature.

**Comment by bristol-d** [comment]
Thank you! That's the quickest and best kind of response you can get from a developer, and I'll happily keep it active on my browser now.

**Comment by sewerynkalemba** [comment]
@bristol-d,

I replaced `tabs` permission with `activeTab` and it should not scare as much as the previous one did. :) 

Thank you for the issue, it's always better to have the features work the way the worked before and access less user's data at the same time.
